Frontend loginpage
Jaffenheimer/p7-internet pull request #107
Opened 2023-10-23 08:23 UTC by sebxGit

Functionality:

A separate page where you can login/create a user
A login button that changes to profile icon if you are logged in
Username and Password validation on user creation
Logout via. the dropdown menu at the profile icon.
A back arrow on login page that navigates back to the front page

2023-10-23 09:38 UTC, Jaffenheimer approved these changes
Det ser fint ud

2023-10-23 12:41 UTC, Lildhansen requested changes
Synes ikke login knappen skal være den samme knap som de andre i applikationen (og den er også ret stor og passer ikke ind, men det bliver vel fixed når vi får topbar)

Er stadig heller ikke fan af at det er en toggle (om det er create user eller login) - synes ikke det er særligt intuitivt

2023-10-23 12:41 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +                        <a href="#">Glemt kodeord?</a>
kommer vi til at lave noget funktionalitet for det her overhovedet?

2023-10-23 12:41 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +    else if (checkValidPassword() === false)		toast.error("Kodeordet skal bestå af mindst et tal, et stort bogstav, et lille bogstav og være mellem 6 og 20 characters langt uden brug af specielle cha
tegn i stedet for characters?

2023-10-23 12:41 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +    else if (checkValidUsername() === false)	 	toast.error("Brugernavnet er invalid, da det kun må bestå af bogstaver og tal.")
ugyldigt*
i stedet for invalid

2023-10-23 12:41 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +                    <h3> Login/Tilføj Bruger
synes det burde være lav bruger i stedet

du vil jo heller ikke sige add user, men create user

2023-10-23 12:41 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +        toast.error("Din bruger er nu tilføjet til databasen!")
måske der skulle tilføjes en comment her at der skal indsættes at brugeren faktisk er tilføjet - fordi lige nu er det vel bare en toast

Og btw hvorfor er det en toast.error
går ud fra der er andre toasts, kan vi så ikke bruge dem her

2023-10-23 12:41 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +		dispatch(pageActions.goToPage(Pages.frontPage)) //goto start page again
burde man ikke gå tilbage til den side man kom fra i stedet

2023-10-23 12:41 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/ProfilePicture.jsx
> +  const handleFavourites = () => {
hov hov troede vi skrev amerikansk

2023-10-23 12:41 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +    // skal der håndteres hvis validUser.length > 1?
?
det er vel det du gør nu

2023-10-23 12:41 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +    // skal der håndteres hvis validUser.length > 1?
eller er det hvis der er mere end 1 user logged in- fordi det er vel ikke muligt

2023-10-23 12:41 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +    if(validUser.length === 1){
kunne godt tænke mig en comment.
betyder det bare at man er logged in

2023-10-23 12:41 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +  function checkValidUsername(){
er der en grund til vi har det her validation.
altså generelt set er det jo security  concerns, men det er vi da ligeglad med i vores program (det ser vi i hvert fald ikke på overhovedet ellers)

2023-10-23 12:41 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +        toast.error("Din bruger er nu tilføjet til databasen!")
kunne også være fedt hvis den skrev:
bruger *indsæt brugernavn* er nu ...

2023-10-23 14:22 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +                        <a href="#">Glemt kodeord?</a>
Det er mere en placeholder, altså det er ved alle login skærme, så synes det er fint at have som prove of concept

2023-10-23 14:22 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +    else if (checkValidPassword() === false)		toast.error("Kodeordet skal bestå af mindst et tal, et stort bogstav, et lille bogstav og være mellem 6 og 20 characters langt uden brug af specielle cha
sure, ændrer det

2023-10-23 14:23 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +    else if (checkValidUsername() === false)	 	toast.error("Brugernavnet er invalid, da det kun må bestå af bogstaver og tal.")
fixed.

2023-10-23 14:24 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +                    <h3> Login/Tilføj Bruger
Ændrede det til opret bruger, tror det er mest brugt.

2023-10-23 14:25 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +        toast.error("Din bruger er nu tilføjet til databasen!")
har tilføjet begge, bruger også toast.success nu.

2023-10-23 14:27 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +		dispatch(pageActions.goToPage(Pages.frontPage)) //goto start page again
troede kun at man kunne se profil icon fra start siden, ændrer det når den er visible for alle sider.

2023-10-23 14:28 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +		dispatch(pageActions.goToPage(Pages.frontPage)) //goto start page again
har lavet en issue til det

2023-10-23 14:29 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/ProfilePicture.jsx
> +  const handleFavourites = () => {
fixed.

2023-10-23 14:29 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/ProfilePicture.jsx
> +  const handleFavourites = () => {
du er en værre en

2023-10-23 14:30 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +    // skal der håndteres hvis validUser.length > 1?
Det er ikke muligt, men tænker hvis nu der var en fejl på en eller anden måde

2023-10-23 14:32 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +    if(validUser.length === 1){
done

2023-10-23 14:33 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +  function checkValidUsername(){
Som jeg også sagde til Jonathan er det noget midlertidigt, da det helst skal ske i backend. Jeg har bare regex så noget af funktionaliteten fra brugerens side matcher, hvad de kan gøre lige nu.

2023-10-23 17:13 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +                    <h3> Login/Tilføj Bruger
ja det er bedre

2023-10-23 17:13 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +                        <a href="#">Glemt kodeord?</a>
fair

2023-10-23 17:15 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +    // skal der håndteres hvis validUser.length > 1?
så er der andre problemer end bare det. synes ikke vi skal have det med

2023-10-23 17:15 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +  function checkValidUsername(){
fair

2023-10-23 17:17 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +		//validUser finds users on Redux matches the username and password typed.
hvad betyder et redux match

2023-10-24 06:22 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/LoginPage.jsx
> +		//validUser finds users on Redux matches the username and password typed.
ah okay. det var bare en stavefejl. retter lige

2023-10-24 07:45 UTC, JJTM20 commented
Backenden understøtter at man kan indtaste en email. Kan heller ikke se hvordan "glemt kodeord"-knappen skal kunne have en funktion uden en email at sende instruktioner til. Så det kunne være nice at tilføje ihvertfald:)

2023-10-24 07:47 UTC, JJTM20 commented
Derudover kunne det være nice hvis det var en modal der ligger "ovenpå" siden i stedet for en helt ny side

React modal: https://reactjsexample.com/login-modal-component-built-with-react/

2023-10-24 07:52 UTC, Lildhansen commented
det ser fint ud i fht. mine codecomments, men er stadig ikke helt fan af stuff jvf. de ting jeg skrev i første comment

2023-10-24 07:54 UTC, Lildhansen commented
hvis det var en "modal" ville det nok også fixe det med at man ender på samme side som man startede efter log in

2023-10-24 08:30 UTC, sebxGit commented
kan godt gøre det til en modal, gør jeg lige så.

2023-10-24 14:25 UTC, sebxGit commented
> Synes ikke login knappen skal være den samme knap som de andre i applikationen (og den er også ret stor og passer ikke ind, men det bliver vel fixed når vi får topbar)
> 
> Er stadig heller ikke fan af at det er en toggle (om det er create user eller login) - synes ikke det er særligt intuitivt

Jeg laver ikke så meget på designet, da de nyeste farver /design skal ind, før vi/jeg træffer beslutninger der. Ift. toggle knappen synes jeg det virker fint, da jeg ikke vil gøre meget ud af at gøre det meget "pænere" med en knap, da det igen kun er proof of concept og det bare skal vise, at man kan gemme på hearted recipes.

2023-10-25 12:57 UTC, Lildhansen commented
hvorfor er ikonet der nu kun når man trykker login. det giver vel mere mening at have når man vil lave en bruger (selvom jeg stadig vil argumentere for det ikke burde være der)

fair nok i fht knappen, men så skal jeg nok lave det til et link i stedet for en toggle

2023-10-25 12:58 UTC, Lildhansen commented
og hvorfor skal man indtaste sit fulde navn?

2023-10-25 13:23 UTC, Lildhansen commented
har ændret så det er en toggle nu. det med knappen må vi se på senere.
er stadig ikke med på hvorfor man skal indtaste sit fulde navn though

2023-10-26 07:06 UTC, sebxGit commented
> og hvorfor skal man indtaste sit fulde navn?
fuld navn er væk nu

2023-10-26 10:34 UTC, NikolajKrogh reviewed
Dejligt med kommentarer til koden

2023-10-26 10:34 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/components/ContainerRight.jsx
> +const customStyles = {
Hvorfor ligger det ikke i CSS?

2023-10-26 10:34 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/components/ContainerRight.jsx
> +  //DELETE WHEN MODAL IS DONE.
Is modal done?

2023-10-26 10:34 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/components/LoginBox.jsx
> +  //THE USERNAME VALIDATION SHOULD HAPPEN IN THE BACKEND
Hvorfor sker det så her?

2023-10-26 10:37 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/ContainerRight.jsx
> +  //DELETE WHEN MODAL IS DONE.
yes

2023-10-26 10:40 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/LoginBox.jsx
> +  //THE USERNAME VALIDATION SHOULD HAPPEN IN THE BACKEND
fordi det ikke er koblet sammen med backend endnu

2023-10-26 11:09 UTC, NikolajKrogh approved these changes
lgtm

2023-10-26 11:10 UTC, Lildhansen approved these changes
jsdsfu

2023-10-26 11:13 UTC, merged