Can get geolocation of user and saves it to browsers localStorage
Jaffenheimer/p7-internet pull request #116
Opened 2023-10-24 09:23 UTC by JJTM20

Prompts the user to access geolocation data and saves it to localStorage

2023-10-24 09:34 UTC, Jaffenheimer approved these changes
Noice

2023-10-24 09:53 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/GenerateRecipeButton.jsx
> +    } else toast("Geolocation not supported");
har svært ved at se hvad brugeren skal bruge denne toast til. de aner vel ikke hvad de skal gøre i fht geolocation

2023-10-24 09:54 UTC, Lildhansen requested changes
^
 |
 |

2023-10-24 18:24 UTC, Jaffenheimer approved these changes
Tilfredstillende ændring tænker jeg så approver igen

2023-10-24 18:24 UTC, Jaffenheimer commented on P7Internet.Frontend/react-app/src/components/GenerateRecipeButton.jsx
> +    } else toast("Geolocation not supported");
Er ændret

2023-10-25 12:44 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/GenerateRecipeButton.jsx
> +    } else toast("Geolocation not supported");
oversætter den lige til dansk, så er den finno

2023-10-25 12:45 UTC, Lildhansen submitted a review, later dismissed
lgtm

2023-10-25 12:50 UTC, Lildhansen requested changes
det ser umiddelbart fint ud udover jeg ikke helt forstår hvordan jeg allower noget geolokation (der kommer ingen popup / eller toast for den sags skyld)

2023-10-25 12:52 UTC, Lildhansen approved these changes
okay nvm, troede der vil kommer noget popup men min accepterer det bare

2023-10-26 06:58 UTC, merged