Added email confirmation, password reset and change password endpoints
Jaffenheimer/p7-internet pull request #145
Opened 2023-10-28 15:50 UTC by Jaffenheimer

The application now sends an email for verification (not done, need front-end implementation) sends an email if you request you password to be reset, and created support for changing of password as well.

2023-10-31 09:16 UTC, JJTM20 requested changes

2023-10-31 09:16 UTC, JJTM20 commented on P7Internet.Persistence/UserRepository/UserRepository.cs
> +        var checkIfUserExist = await GetUser(userName);
Why not just "user"?

2023-10-31 09:16 UTC, JJTM20 commented on P7Internet.Persistence/UserRepository/UserRepository.cs
> +        var checkIfUserExist = await GetUser(userName);
Same as below

2023-10-31 09:16 UTC, JJTM20 commented on P7Internet.Persistence/UserRepository/UserRepository.cs
> +        var result = await Connection.ExecuteAsync(query, new {Name = userName, Email = emailAddress});
"Name" should be removed and and "Email" should be "email" to correspond to the query parameters.

2023-11-02 08:04 UTC, Jaffenheimer commented on P7Internet.Persistence/UserRepository/UserRepository.cs
> +        var result = await Connection.ExecuteAsync(query, new {Name = userName, Email = emailAddress});
Ændret

2023-11-02 08:04 UTC, Jaffenheimer commented on P7Internet.Persistence/UserRepository/UserRepository.cs
> +        var checkIfUserExist = await GetUser(userName);
Ændret

2023-11-02 08:04 UTC, Jaffenheimer commented on P7Internet.Persistence/UserRepository/UserRepository.cs
> +        var checkIfUserExist = await GetUser(userName);
ændret

2023-11-02 08:25 UTC, JJTM20 approved these changes

2023-11-02 09:22 UTC, merged