Pretty-prints recipe + added minor fixes to css
Jaffenheimer/p7-internet pull request #148
Opened 2023-10-31 14:35 UTC by JJTM20

2023-10-31 14:37 UTC, JJTM20 commented
Måske skal det være 'udskriv' i stedet for 'print'?

2023-11-01 08:47 UTC, NikolajKrogh requested changes
Tror du har sat prettier op på en anden måde end os andre, fordi hvis jeg prøver at formatere koden så rykker den bare alt tilbage hvor det var. Tænker du har prettier sat til at lave fire mellemrum og vi andre har den til to.

I vs code kan gå til File > Preferences > Settings også søge efter prettier

2023-11-01 08:47 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/pages/FullRecipeView.jsx
> +        //pt har vi ikke den side, så det er bare frontpage
Hvilken side er det  vi mangler?

2023-11-01 08:47 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/App.css
> +}
Jeg havde lidt svært ved at se hvad det gjorde, så måske en kommentar fx:

```
/* Apply style only when printing */
@media print {
    /* Targets any HTLM element with the no-print */
    .no-print,
    /* Targets any child elements of an element with the class no-print. */
    .no-print * {
        display: none !important;
    }
    /* Modify the printed page */
    @page {
        margin: 0;
    }
}
```

2023-11-01 08:47 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/pages/FullRecipeView.jsx
> +                <div className="bottomButtons no-print">
Jeg troede vi havde Pascal casing, men der bliver både brugt Pascal og camel, men her bliver ingen af dem overholdt

2023-11-01 12:51 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/FullRecipeView.jsx
> +        //pt har vi ikke den side, så det er bare frontpage
det er en kommentart jeg lavede før vi havde delt den første side op i 2.
nu skal den bare linke til siden før i stedet for front page

2023-11-01 12:51 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/FullRecipeView.jsx
> +                <div className="bottomButtons no-print">
burde være pascal, ja

2023-11-01 23:22 UTC, JJTM20 commented
> Tror du har sat prettier op på en anden måde end os andre, fordi hvis jeg prøver at formatere koden så rykker den bare alt tilbage hvor det var. Tænker du har prettier sat til at lave fire mellemrum og vi andre har den til to.
> 
> I vs code kan gå til File > Preferences > Settings også søge efter prettier

Ah okay, det får jeg lige fixet imorgen

2023-11-02 10:41 UTC, Lildhansen commented
> Måske skal det være 'udskriv' i stedet for 'print'?

det betyder ikke det store for mig

2023-11-02 11:29 UTC, NikolajKrogh approved these changes

2023-11-03 11:05 UTC, merged