Frontend save previous recipes
Jaffenheimer/p7-internet pull request #154
Opened 2023-11-01 16:11 UTC by sebxGit

A continuation of the PR: "Hearing Recipes Now Requires Login".
A user can now save previously hearted recipes via. profile icon > favoritter. Here, they can inspect the hearted recipes and select one of them, which will move them to the FullRecipeView page, where they can see the full recipe that was generated.

Functionality:
- The user should be able to see a message in the favoritter modal, that no recipe is hearted, if that is the case.
- To generate recipes, one have to go to the second page, where the three recipes are generated.
- The user can now select a hearted recipe.
- Please see if >15 recipes and scrolling works in the favoritter modal by adding 15+ recipe titles in the heartedRecipes list, found in react-app>src>features>userSlice.js.
- The user should be not be able to select a favorited recipe, which is not found in the recipe list. This should show an error message.

2023-11-03 08:17 UTC, Lildhansen commented
burde vi have noget med at man kunne slette favorited recipes i denne menu også - synes kunne være nice i hvert fald

2023-11-03 08:18 UTC, Lildhansen commented
og kunne være fed hvis det kunne ændres så man ikke kan scrolle selve siden når modal er open, men kunne ikke helt få det til at virke

2023-11-04 17:16 UTC, Lildhansen commented
where them tests at?

2023-11-05 11:42 UTC, sebxGit commented
Synes ikke man behøver det med at unfavorite i menuen, da man nemt kan gøre det i fullrecipeview siden. Tror det ville skabe forvirring i menuen, men hvis folk stemmer for det, kan jeg godt lave det snildt.

2023-11-05 12:43 UTC, sebxGit commented
har added tests nu, men kan ikke få jest til at køre RecipeView, da den bruger redux tror jeg, får error ihf.

2023-11-08 08:31 UTC, Lildhansen commented
forstår ikke det double click når man kan se i funktionen at den kalder onclick hver gang man trykker på den

2023-11-08 08:34 UTC, Lildhansen requested changes
generelt set vil jeg mene at vi burde teste alle components, så favoritesBox burde vel også testes

og der kan man måske finde fejlen i fht. det double click

2023-11-08 11:12 UTC, Lildhansen commented
der mangler stadig test men jeg kan godt lave dem for det jeg lige lavede

2023-11-08 16:23 UTC, Lildhansen commented
burde de favorite recipes ikke blive storet som recipe objekter i stedet for bare deres titel

så behøver vi heller ikke at sammenligne med "recipes" og så det med at hvis opskriften ikke er på databasen

2023-11-09 08:07 UTC, Lildhansen approved these changes

2023-11-09 08:38 UTC, merged