Frontend radiusslider
Jaffenheimer/p7-internet pull request #160
Opened 2023-11-02 13:09 UTC by sebxGit

Added radiusslider

Functionality:
- radius slider uses log and have a larger span for smaller values and smaller span for larger values
- radius slider requires geolocation, and you have to allow geolocation and reload, if it was not allowed when the user enters the second page
- The toggle should switch between one of the components, each being radius and select stores.

(no backend integration is made, the radius is accessible via. its hook: sliderValue in RadiusSlider.jsx)

2023-11-03 13:00 UTC, JJTM20 approved these changes
Looks good

2023-11-04 16:45 UTC, Lildhansen requested changes
nu når testing frameworket er sat op synes jeg vi skal teste de components vi laver

synes også man burde kunne skrive radius ind (og once again har jeg svært ved at se hvorfor den skal gå helt op til 700, i stedet for bare at have en slage uendelig radius, hvor vi så sætter det til max value: 700)


> radius slider requires geolocation, and you have to allow geolocation and reload, if it was not allowed when the user enters the second page

Kan også se at hvis jeg blokerer den fra at acesse min lokation, kan jeg stadig bruge slideren, det burde vel ikke være muligt

2023-11-04 16:59 UTC, Lildhansen requested changes

2023-11-04 16:59 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/RadiusSlider.jsx
> +        <p>Radius: {filterSliderValue(logSlider(sliderValue))}</p>
er underligt det bare er en p, da skriftstørrelsen ikke er så consistent. synes det burde være i think h3 som mulige butikker fx også er

2023-11-04 16:59 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/RadiusSlider.jsx
> +    var maxv = Math.log(700000);
synes vi var enige om ikke at bruge forkortelser.
kan vi kalde det value og position i stedet

2023-11-04 16:59 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/RadiusSlider.jsx
> +  function logSlider(position) {
synes ikke funktionsnavnet er særligt sigende. den logger vel ikke en slider. den beregner vel slide valuen eller hvad (tilføje også gerne en comment til den)

2023-11-04 16:59 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/RadiusSlider.jsx
> +    var inv = 1.0 / step;
igen, "inverse"?

2023-11-04 16:59 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/RadiusSlider.jsx
> +  function round(value, step) {
og hvad betyder step?

2023-11-04 16:59 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/ToggleButton.jsx
> +    </div>
hvorfor har vi inline style i stedet for i CSS'en

2023-11-04 17:15 UTC, Lildhansen commented
jeg er ikke helt sikker på om det er intuitivt at den du har valgt i den toggle er med hvid og den anden med grå.
jeg vil i hvertfald tænke at den med grå er noget jeg har trykket på og derfor er den jeg har valgt.
måske andre farver kunne bruges som er mere intuitive

2023-11-05 12:51 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/RadiusSlider.jsx
> +        <p>Radius: {filterSliderValue(logSlider(sliderValue))}</p>
<img width="475" alt="image" src="https://github.com/Jaffenheimer/p7-internet/assets/72699667/d3db7b0c-c874-4454-baab-f2042d91d284">
Synes det er voldgrimt med h3, det er derfor jeg valgte p

2023-11-05 12:52 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/RadiusSlider.jsx
> +    var maxv = Math.log(700000);
fixed.

2023-11-05 12:56 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/RadiusSlider.jsx
> +  function logSlider(position) {
fixed.

2023-11-05 12:56 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/RadiusSlider.jsx
> +    var inv = 1.0 / step;
fixed.

2023-11-05 12:58 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/RadiusSlider.jsx
> +  function round(value, step) {
fixed

2023-11-05 12:59 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/ToggleButton.jsx
> +    </div>
Har ændret det så det er en klasse for borderRadius. Men BackgroundColor skal applies i jsx filen, da background color skal defines efter css'en, så den får den reelle farve som den skal være. Ellers breaker det.

2023-11-05 13:01 UTC, sebxGit commented
Jeg synes det er meget intuitivt, da den kommer i baggrunden, når du trykker på en anden knap. Hvad siger jer andre?

2023-11-06 07:59 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/RadiusSlider.jsx
> +        <p>Radius: {filterSliderValue(logSlider(sliderValue))}</p>
ved heller ikke om jeg synes de 100 m skal stå i h3

2023-11-06 09:10 UTC, NikolajKrogh commented
> Jeg synes det er meget intuitivt, da den kommer i baggrunden, når du trykker på en anden knap. Hvad siger jer andre?

Jeg synes det fungerer godt at den er hvid når man klikker på den, men i stedet for at den er grå kan den måske have samme styling som resten af vores knapper, så det er tydeligt at se man kan trykke på den

2023-11-06 09:11 UTC, NikolajKrogh commented
Er det muligt at gemme radius når man klikke over på butikker? Fordi lige nu nustiller den bare og går tilbage til 100m, og det kunne være nice hvis den huskede hvad man havde sat den til

2023-11-06 11:35 UTC, sebxGit commented
> Er det muligt at gemme radius når man klikke over på butikker? Fordi lige nu nustiller den bare og går tilbage til 100m, og det kunne være nice hvis den huskede hvad man havde sat den til

Kræver jeg adder redux og andet, laver det næste gang jeg laver projekt.

2023-11-07 08:53 UTC, NikolajKrogh approved these changes
lgtm

2023-11-09 08:41 UTC, Lildhansen approved these changes

2023-11-09 09:10 UTC, merged