Added Salling API service + Testing
Jaffenheimer/p7-internet pull request #162
Opened 2023-11-04 15:32 UTC by JJTM20

2023-11-04 17:04 UTC, Lildhansen reviewed
har sat lidt comments.
kan ikke helt huske hvordan jeg åbner det swagger så vil gerne have en lille guide til det hvis jeg skal teste det

2023-11-04 17:04 UTC, Lildhansen commented on P7Internet.Test/ServiceTests.cs
> +        public async Task GetSallingOffersSuccess()
forespørger vi nu etilbudsavis hver gang vi kører tests?

2023-11-04 17:04 UTC, Lildhansen commented on P7-internet.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "P7Internet.Shared", "P7Internet.Shared\P7Internet.Shared.csproj", "{5AE8E67C-855B-4822-96A6-57B68DD4D7FF}"
burde dette ikke gitignores - eller er det vigtigt alle får ændringen?

2023-11-04 17:04 UTC, Lildhansen commented on P7Internet.RestApi/Services/SallingService.cs
> +            url = new Uri(QueryHelpers.AddQueryString(url.ToString(), "query", query));
hvorfor sættes den til en værdi hvorefter den så overskrives lige efter

2023-11-04 20:15 UTC, JJTM20 commented on P7Internet.Test/ServiceTests.cs
> +        public async Task GetSallingOffersSuccess()
> forespørger vi nu etilbudsavis hver gang vi kører tests?

Niks. Vi forespørger derimod Salling, hvor vi har 10.000 månedlige requests.

2023-11-04 20:15 UTC, JJTM20 commented on P7-internet.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "P7Internet.Shared", "P7Internet.Shared\P7Internet.Shared.csproj", "{5AE8E67C-855B-4822-96A6-57B68DD4D7FF}"
Det burde det vel egentlig

2023-11-04 20:16 UTC, JJTM20 commented on P7Internet.RestApi/Services/SallingService.cs
> +            url = new Uri(QueryHelpers.AddQueryString(url.ToString(), "query", query));
Mest for at undgå en kilometerlang linje, men fikser lige.

2023-11-06 07:57 UTC, Lildhansen commented on P7Internet.Test/ServiceTests.cs
> +        public async Task GetSallingOffersSuccess()
ah jaer okay. i see

2023-11-06 07:58 UTC, Lildhansen commented on P7Internet.RestApi/Services/SallingService.cs
> +            //url = new Uri(QueryHelpers.AddQueryString(url.ToString(), "query", query));
hvorfor udkommenterer du det bare så

2023-11-06 07:58 UTC, Lildhansen commented on P7Internet.RestApi/Services/SallingService.cs
> +            url = new Uri(QueryHelpers.AddQueryString(url.ToString(), "query", query));
men nu er det jo bare udkommenteret

2023-11-07 11:07 UTC, Lildhansen requested changes
den kører ikke backend CI

2023-11-08 08:08 UTC, Casper0913 commented
<img width="780" alt="Skærmbillede 2023-11-08 kl  09 06 02" src="https://github.com/Jaffenheimer/p7-internet/assets/48017776/97243ab0-14a6-42f2-8a7f-5ba4c0e869d8">

Har testet endpoint og får data derfra og testene virker også for mig. 

Skal vi have en limit på mange ingredienser den fecther, da den ved mit test fandt 10 forskellige ingredienser 

Ved mig bliver ingredienserne ikke cached i database også efter jeg har drop og bygget en ny
<img width="327" alt="Skærmbillede 2023-11-08 kl  09 42 13" src="https://github.com/Jaffenheimer/p7-internet/assets/48017776/a8589b27-8f08-4691-961b-6e763f803df9">

Nogle af ingredienserne fra bilka har ikke store navn, ved ikke om det kan give problemer, hvis vi finder chached offers ud fra store navn?
<img width="110" alt="Skærmbillede 2023-11-08 kl  09 43 16" src="https://github.com/Jaffenheimer/p7-internet/assets/48017776/35d8f4db-dc53-40fb-8876-3076b21092a6">

2023-11-09 07:28 UTC, JJTM20 commented
> <img alt="Skærmbillede 2023-11-08 kl 09 06 02" width="780" src="https://private-user-images.githubusercontent.com/48017776/281309819-97243ab0-14a6-42f2-8a7f-5ba4c0e869d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTk1MTQ5NzgsIm5iZiI6MTY5OTUxNDY3OCwicGF0aCI6Ii80ODAxNzc3Ni8yODEzMDk4MTktOTcyNDNhYjAtMTRhNi00MmYyLThhN2YtNWJhNGMwZTg2OWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTA5VDA3MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljOGM5MmQ4ZTM3ZjIwNzcyNWMzZjE4ZTAxNTQ5ZTMyZjkwY2M0YTFmNDljOTI1NThkMDc3N2M5NjJjNjRhMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.92tFZRerTEYuWQqLRucISQNOXPptYH0ZXAAWjyixmwM">
> Har testet endpoint og får data derfra og testene virker også for mig.
> 
> Skal vi have en limit på mange ingredienser den fecther, da den ved mit test fandt 10 forskellige ingredienser
> 
> Ved mig bliver ingredienserne ikke cached i database også efter jeg har drop og bygget en ny <img alt="Skærmbillede 2023-11-08 kl 09 42 13" width="327" src="https://private-user-images.githubusercontent.com/48017776/281325720-a8589b27-8f08-4691-961b-6e763f803df9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTk1MTQ5NzgsIm5iZiI6MTY5OTUxNDY3OCwicGF0aCI6Ii80ODAxNzc3Ni8yODEzMjU3MjAtYTg1ODliMjctOGYwOC00NjkxLTk2MWItNmU3NjNmODAzZGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTA5VDA3MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNGMwZWI2N2UwOTdlNDJiMWIzYjg1NjAzOWIwMWQ4NGNhY2RiZWRlMDVmNGFlMWYxZmI4M2MwYmJiMDRlNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Niekk5z85qPw3lzMJpDVIBBGwzuD8DhrhNIqhYAhQHc">
> 
> Nogle af ingredienserne fra bilka har ikke store navn, ved ikke om det kan give problemer, hvis vi finder chached offers ud fra store navn? <img alt="Skærmbillede 2023-11-08 kl 09 43 16" width="110" src="https://private-user-images.githubusercontent.com/48017776/281326016-35d8f4db-dc53-40fb-8876-3076b21092a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTk1MTQ5NzgsIm5iZiI6MTY5OTUxNDY3OCwicGF0aCI6Ii80ODAxNzc3Ni8yODEzMjYwMTYtMzVkOGY0ZGItZGM1My00MGZiLTg4NzYtMzA3NmIyMTA5MmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTA5VDA3MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NDg0YmIzZGZhNDgxNmNiMjA3ZGFlMDI0YTY1ZDU0NjQyY2I5MmEwZWVhZjZhZTk0MGI3ODBjOGUwNGUwNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eWJ7UnLxCDDN38GjE8GQ9_17SzlfoE8RdY4iejH9Eq0">

Uha, den burde ellers sætte alt fra Sallings API til BilkaToGo. Det får jeg lige kigget på i dag (torsdag) ;)

2023-11-13 07:36 UTC, Lildhansen approved these changes
nice

2023-11-14 07:36 UTC, merged