Develop connect frontend to backend (Create User, Login User, Logout user)
Jaffenheimer/p7-internet pull request #172
Opened 2023-11-08 07:26 UTC by Casper0913

### **Jeg har tilføjet forbindelse mellem frontend og backend ved følgende:** 
- Create user
- Login user
- Logout user

### **Til som skal gøre inden man kan test**
**1. Sikre sig at man køre den nyeste database**, da det eller ville give fejl
    (Man opdatere ved brug af Dbup mappen, måske skal man droppe ens tabel inden man opdatere)
**3. At man køre både: docker (databasen), restapi og frontenden**

### **Ting som man kan teste**
1. Når man laver en bruger, kan man det og bliver den også lavet i databasen
2. Når man logger ind, kan man det og bliver der lavet en token til brugeren ind i database
3. Når man logger ud, virker det og bliver alt data omkring user i store fjernet

2023-11-08 08:43 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/ProfilePicture.jsx
> +        toast.error("Kunne ikke loge ud", error);
typo: loge --> logge

2023-11-08 08:44 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/RecipeTitle.jsx
> +  const loggedIn = useSelector((state) => state.user.loggedInd);
hvorfor hedder det loggedIn et sted og loggedInd det andet sted? Foretrækker et consistent navn, og helst loggedIn, da vores program er skrevet på engelsk de andre steder ihf.

2023-11-08 08:53 UTC, Casper0913 commented on P7Internet.Frontend/react-app/src/components/ProfilePicture.jsx
> +        toast.error("Kunne ikke loge ud", error);
Sådan har fikset det i ny commit

2023-11-08 08:53 UTC, Casper0913 commented on P7Internet.Frontend/react-app/src/components/RecipeTitle.jsx
> +  const loggedIn = useSelector((state) => state.user.loggedInd);
Har fikset dette i det ny commit.

2023-11-09 08:58 UTC, sebxGit approved these changes

2023-11-09 10:11 UTC, Lildhansen requested changes

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/services/apiSlice.js
> +*/
translate plz

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/services/apiSlice.js
> +*/
gælder for alle kommentarene

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/testdata/testUser.json
> +}
bliver det her brugt til tests nogen steder eller hvordan

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/helperFunctions/retriveCookie.js
> +const retriveCookie = (retriveValue) => {
synes godt denne funktion kunne testes.
måske hvis man selv skal passe cookies med som argument, og så kan man mocke dem i testen

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/GenerateRecipeButton.jsx
> +//import { recipeGenerationActions } from "../features/recipeGenerationSlice";
plz delete

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/LoginBox.jsx
> +    //Functions from redux that allows to test weather error or loading
synes kommentaren skal sigehvad if'en betyder, fx (uden jeg helt ved hvad den gør):
if login is not loading or there are no errors when logging in

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/LoginBox.jsx
> +          toast.error("Kodeordet eller brugernavnet er indtastet forkert");
det skal ændres til noget andet. burde det overhovedet være en toast, det kan vel ikke være brugerens skyld hvis vi ender her eller hvad?

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/LoginBox.jsx
> +      //Functions from redux that allows to test weather error or loading
samme comment som ovenover

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/LoginBox.jsx
>      else {
der er ret meget kodeduplikering. kunne det komme ud i funktioner eventuelt

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/LoginBox.jsx
>      else {
altså login og create user

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/ProfilePicture.jsx
> +      //console.log(`Retrived tokens: UserId: ${userId}, sessionToken: ${sessionToken}`);
remove plz

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/ProfilePicture.jsx
> +          //console.log(response);
remove plz

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/ProfilePicture.jsx
> +        toast.error("Kunne ikke logge ud", error);
printer vi erroren nu til brugeren. det lyder ikke særlig repræsentabelt for brugeren

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/ProfilePicture.jsx
> +          toast.success("Logget ud");
kunne det ikke stå mere som en sætning.
fx "du loggede succesfuldt ud" eller såen

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/ProfilePicture.jsx
>      setOpen(false);
what is this

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/ProfilePicture.jsx
>      setOpen(false);
du har også tilføjet true senere

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/RecipeTitle.jsx
>        //if not logged in
nu når du har ændret if'en synes jeg ikke comment er nødvendig

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/RecipeTitle.jsx
> +        //console.log(heartedRecipes);
yeet plz

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/RecipeTitle.jsx
> +        //console.log(heartedRecipes);
hele if'en vel, fordi vi har ingen error handling for det (ellers skal der tilføjes error handling)

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/features/userSlice.js
> +      state.heartedRecipes = [];
det er lidt wack vi resetter hearted recipes når man logger ind.

2023-11-09 10:11 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/helperFunctions/generateOpenAiString.js
> +//Skal fjernes når endpoint er klar. Blev lavet for at kunne test OpenAi
plz remember to remove

2023-11-13 07:27 UTC, Lildhansen approved these changes

2023-11-13 07:27 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/ProfilePicture.jsx
> +        toast.error("Kunne ikke logge ud", error);
det samme for toasten med ikke kunne lave en bruger. synes ikke det burde være en toast men at vi regel håndterer det fordi det har vel intet med brugeren at gøre

2023-11-13 07:45 UTC, merged