fixet så den kun tjekker om du har valgt butikker hvis du er under "vælg butikker". har ændret på storeslice så den dækker mere end bare stores (offerSlice nu)
Jaffenheimer/p7-internet pull request #181
Opened 2023-11-09 12:16 UTC by Lildhansen

2023-11-10 07:56 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/RadiusSlider.jsx
> +      <h3>Radius:</h3>{" "}
Hvorfor bruger du {" "} her?

2023-11-10 08:00 UTC, NikolajKrogh requested changes
Den gemmer ikke længere radius når man skifter til butikker.
Så jeg ændrer radius til 7 km går til butikker og tilbage til radius, så er radius 100m igen

2023-11-10 08:47 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/RadiusSlider.jsx
> +      <h3>Radius:</h3>{" "}
det er bare prettier der formatter. du havde sat mellemrum efter. kan godt slette det

2023-11-10 08:56 UTC, Lildhansen commented
> Den gemmer ikke længere radius når man skifter til butikker. Så jeg ændrer radius til 7 km går til butikker og tilbage til radius, så er radius 100m igen

den husker det heller ikke for stores, fixer lige

2023-11-12 19:19 UTC, Lildhansen commented
det er fixed nu, men der er et problem, med radius.
hvis jeg tilføjer den til slicet og opdaterer hver gang den ændres får den ikke den rigtige værdi.
har oprettet et issue, med det: #186

2023-11-13 08:22 UTC, Casper0913 approved these changes
lgtm

2023-11-13 08:38 UTC, closed without merging