Frontend test
Jaffenheimer/p7-internet pull request #219
Opened 2023-11-15 11:42 UTC by NikolajKrogh

**Der er lavet test for:**
* AddIngredientsForm - Fixes #184 
* dietaryRestrictions - Fixes #188 
* containerLeft (Now renamed to FrontPageContainerLeft) - Fixes #197 
* containerRight (Now renamed to FrontPageContainerRight) - Fixes #198 
* excludeList - Fixes #199 
* header (Ikke lavet så mange test, fordi det meste bruger dispatch) - Fixes #202

2023-11-15 12:50 UTC, Lildhansen requested changes
eftersom du har taget nogle af de "store" komponenter er der selvfølgelig mere arbejde, fordi med dem kan vi nemlig lave en eller anden form for integration testing, da de inkorporerer flere komponenter i sig.

2023-11-15 12:50 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/DietaryRestrictionsTest.jsx
> +    expect(selectElement.value).not.toBe("Veganer");
kunne man ikke bare tilføje denne expect til den forrige test i stedet.

2023-11-15 12:50 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/ExcludeListTest.jsx
> +describe("ExcludeList", () => {
synes der mangler nogle flere dybdegående tests her.
fx:
- at du kan skrive noget i formen og så bliver de displayet i ingredients list
- at den kan displaye flere ingredienser
- at ingen ingredienser er present hvis exclude list er tom 

generelt bare noget med sammenspillet nu når excludelist indeholder ingredientsform og ingredientslist

2023-11-15 12:50 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/FrontPageContainerLeft.jsx
> +describe("FrontPageContainerLeft", () => {
samme kommentar som ovenover (fra exclude list)

2023-11-15 12:50 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/FrontPageContainerRight.jsx
> +describe("FrontPageContainerRight", () => {
her er det anderledes end de 2 andre ovenover, fordi her er det bare flere independent komponenter, så denne her fil er finno tænker jeg

2023-11-15 12:50 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/HeaderTest.jsx
> +describe("Header component", () => {
hvis du kan, må du også gerne teste at der er et brugerikon i højre hjørne hvis man er logget ind og at det åbner de der options under

og så nogle tests for de forskellige options man kan vælge mellem

2023-11-15 12:51 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/DietaryRestrictionsTest.jsx
> +    expect(selectElement.value).not.toBe("Veganer");
fordi det hænger lidt sammen med den ovenover - vegetar er present, veganer er ikke

2023-11-15 12:51 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/DietaryRestrictionsTest.jsx
> +    expect(selectElement.value).not.toBe("Veganer");
man kunne også argumentere for at det er ligegyldigt at teste at den ikke er veganer, fordi den kan ikke have 2 values på samme tid, så det at den er vegetar, betyder også at den så ikke er veganer

2023-11-16 08:05 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/__tests__/DietaryRestrictionsTest.jsx
> +    expect(selectElement.value).not.toBe("Veganer");
Den kan ikke have to values, men hvad er der så galt med at teste det? Jeg vil hellere dele test op end at have det hele i en test

2023-11-16 12:05 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/FrontPageContainerLeft.jsx
> +describe("FrontPageContainerLeft", () => {
også this toast "Du skal tilføje mindst 1 ingrediens for at generere opskrifter"

2023-11-16 12:06 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/FrontPageContainerLeft.jsx
> +describe("FrontPageContainerLeft", () => {
men så at du skriver ingrediensen ind i formen

2023-11-16 13:30 UTC, Lildhansen approved these changes
lmtg

2023-11-16 13:32 UTC, merged