Frontend addingtests
Jaffenheimer/p7-internet pull request #234
Opened 2023-11-23 10:38 UTC by sebxGit

2023-11-23 12:58 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/__tests__/AddIngredientsInputTest.jsx
> +  renderComponent(<AddIngredientInput placeholder="Tilføj en ingrediens..." />);
Det her skal bare slettes
kh Mads

2023-11-23 12:58 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/__tests__/LoginBoxTest.jsx
> +
Det her tester ikke noget

2023-11-23 12:58 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/__tests__/ProfilePictureTest.jsx
> +// test("Profile Picture image is clickable and log out is clickable", () => {
Det her skal nok fjernes

2023-11-23 12:58 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/components/LoginBox.jsx
> +            <a href="/#" aria-label="glemtKodeord">
Engelsk navn

2023-11-23 12:58 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/components/LoginBox.jsx
> +            <a href="/#" aria-label="glemtKodeord">
Måske bruge data-testid

2023-11-23 12:58 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/components/LoginBox.jsx
> +            <a href="/#" aria-label="glemtKodeord">
Den bliver ikke brugt, så du kan også bare slette

2023-11-23 12:58 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/components/SelectArrows.jsx
> +      aria-label="SelectArrows"
data-testid

2023-11-23 13:00 UTC, Lildhansen requested changes

2023-11-23 13:00 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/LoginBoxTest.jsx
> +  // expect(global.window.location.href).toContain('http://localhost/')
kan vi fjerne det her?

2023-11-23 13:00 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/LoginBox.jsx
> +            <a href="/#" aria-label="glemtKodeord">
kan se dette labe ikke bliver refereret andre steder - maybe delete label

2023-11-23 13:00 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/SelectArrows.jsx
> +      aria-label="SelectArrows"
dette aria-label bliver heller ikke reffet - maybe delete

2023-11-23 13:03 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/__tests__/ProfilePictureTest.jsx
> +  expect(screen.queryByText("Favoritter")).not.toBeInTheDocument();
Hvorfor skulle favoritter ikke være der?

2023-11-23 13:25 UTC, Lildhansen requested changes

2023-11-23 13:25 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/StoreSelectionTest.jsx
> +  expect(screen.getByText(/Lidl/)).toBeInTheDocument();
det her tester ikke det du tror, fordi i den react select kan både de ting du har valgt og de ting du ikke har valgt findes, så hvis man ændrer det til alle slags butikker passer testen også (så måske denne expect kan slettes i hvertfald)

2023-11-23 13:25 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/StoreSelectionTest.jsx
> +  expect(buttons.length).toBe(7);
her siger testen heller ikke så meget fordi buttons length er også 7 efter.
og det er også lidt weird vi tester antal buttons når det er en select

2023-11-23 13:25 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/StoreSelectionTest.jsx
> +  expect(buttons.length).toBe(7);
men måske vi bare kan slette linje 46, og så sætte en kommentar ved 45 om at hvert element i react-selecten bliver set som buttons i det Jest DOM når vi render dem

2023-11-23 13:25 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/StoreSelectionTest.jsx
> +  expect(setStoreValues).toHaveBeenCalledTimes(6);
det her synes jeg er valid og nok det eneste vi burde teste

2023-11-24 10:22 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/__tests__/AddIngredientsInputTest.jsx
> +  renderComponent(<AddIngredientInput placeholder="Tilføj en ingrediens..." />);
done.

2023-11-24 10:26 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/LoginBox.jsx
> +            <a href="/#" aria-label="glemtKodeord">
bliver godt nok brugt i den nederste test i loginBoxTests, har ændret det til test-id

2023-11-24 10:26 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/__tests__/LoginBoxTest.jsx
> +
slettet

2023-11-24 10:27 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/__tests__/ProfilePictureTest.jsx
> +// test("Profile Picture image is clickable and log out is clickable", () => {
er fjernet nu

2023-11-24 10:28 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/SelectArrows.jsx
> +      aria-label="SelectArrows"
fixed

2023-11-24 10:28 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/__tests__/LoginBoxTest.jsx
> +  // expect(global.window.location.href).toContain('http://localhost/')
gjort, det var en test som muligvis skulle laves på senere, men tror ikke det kommer til at virke alligevel. Har slettet det.

2023-11-24 10:29 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/LoginBox.jsx
> +            <a href="/#" aria-label="glemtKodeord">
fixed. er blevet ændret til data-testid="forgotPassword"

2023-11-24 10:30 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/__tests__/ProfilePictureTest.jsx
> +  expect(screen.queryByText("Favoritter")).not.toBeInTheDocument();
Når du trykker på dropdownmenuen skal den helst collapse (lukke), hvilket betyder at favoritter ikke er visible mere.

2023-11-24 10:31 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/__tests__/StoreSelectionTest.jsx
> +  expect(screen.getByText(/Lidl/)).toBeInTheDocument();
forstår ikke helt hvad du mener her, skal lige have det uddybet.

2023-11-24 10:33 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/__tests__/StoreSelectionTest.jsx
> +  expect(buttons.length).toBe(7);
fixed. har lavet en kommentar og slettet linje 46

2023-11-24 10:35 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/SelectArrows.jsx
> +      aria-label="SelectArrows"
Den bliver reffet i linje 32 og 33 i SelectArrowsTest, har ændret det til data-testid i stedet

2023-11-24 10:36 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/__tests__/StoreSelectionTest.jsx
> +  expect(setStoreValues).toHaveBeenCalledTimes(6);
altså at vi ikke skal expect lidl er i dokumentet eller hvad mener du?

2023-11-24 12:29 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/ProfilePictureTest.jsx
> +  expect(screen.queryByText("Favoritter")).not.toBeInTheDocument();
skal det så ikke også stå i testen - altså navnet på testen.

2023-11-24 12:29 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/ProfilePictureTest.jsx
> +test("Profile Picture image is clickable and favoritter is clickable", () => {
er ikke helt med på hvad vi tester her med at de er clickable.
altså hvis vi fyrer fireEvent på et h1-element siger den ingenting til det

2023-11-24 12:29 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/StoreSelectionTest.jsx
> +  expect(screen.getByText(/Lidl/)).toBeInTheDocument();
du kan prøve at ændre Lidl til hvilken som helst anden butik og den vil stadig passe.
du kan prøve at skrive noget som den ikke kan finde og så viser den der hvilke elementer der er i DOM'en

2023-11-24 12:30 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/StoreSelectionTest.jsx
> +  expect(screen.getByText(/Lidl/)).toBeInTheDocument();
men vi kan self også kigge på det engang fysisk

2023-11-24 12:30 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/StoreSelectionTest.jsx
> +  expect(setStoreValues).toHaveBeenCalledTimes(6);
ja, fordi lige meget hvad du gør er lidl i dokumentet

2023-11-24 12:48 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/__tests__/ProfilePictureTest.jsx
> +  expect(screen.queryByText("Favoritter")).not.toBeInTheDocument();
gjordt

2023-11-27 14:17 UTC, Lildhansen approved these changes
jsdsfuodajdsbmdi

2023-11-27 14:20 UTC, merged