Facilitate offers
Jaffenheimer/p7-internet pull request #285
Opened 2023-12-11 07:43 UTC by JJTM20

Fixes #237 

Shows price, store image and total price in the FullRecipeView.

2023-12-11 08:04 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/RecipeOfferElement.jsx
> +        //let _radius = toggleStateIsRadius ? radius : 3000; //TODO: INDSÆT DETTE VED MERGE MED DEVELOP
dette skal ændres ved merge med develop. Det gør jeg efter Caspers branch er merget ind i develop

2023-12-11 08:05 UTC, sebxGit commented on P7Internet.Frontend/react-app/src/components/RecipeOfferElement.jsx
> +//#region Helpers
Funktionerne her skal helst ligge over return, da det er sådan react kode skrives generelt, og det kan fke med nogle variabler som man bruger hvis man ikke gør

2023-12-12 09:35 UTC, Lildhansen requested changes
der er flere warnings i frontenden og så er der også et par console.logs,
og jeg kunne heller ikke rigtig få det til at virke

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.Frontend/react-app/.vscode/settings.json
> +{}
?

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/__tests__/StoreSelectionTest.jsx
> +  // Remove all stores but SuperBrugsen by removing the first 9 stores
man kan da ikke slette bilka, er det ikke undtagen den

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/IngredientsList.jsx
> +      <h2>Ingredienser:</h2>
plz remove this - vi har puttet det på de sider vi gerne vil have det i stedet for ingredientslist

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/MethodsList.jsx
> +  console.log("Methods: ", methods);
delete

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/ProfilePicture.jsx
> +        toast.error("Kunne ikke logge ud", error);
synes ikke vi skal skrive hele den error vi får til brugeren (så hellere bare at der skete en uventet fejl og man ikke kan logge ud

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/RecipeOfferElement.jsx
> +      //Empty check should be removed when the empty ingredient issue is fixed
it is not fixed now?

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/helperFunctions/getRecipesFromString.js
> +  //var recipes = [];
?

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/helperFunctions/getRecipesFromString.js
> +function getRecipesFromString(string) {
this should be removed, as it is not used

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/helperFunctions/getRecipesFromString.js
> +function getRecipesFromString(string) {
this entire file that is

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/helperFunctions/ingredientHelper.js
> +  console.log("ingredients: ", ingredients);
de her skal slettes

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/helperFunctions/ingredientHelper.js
> +  console.log(ingredientObjects);
de her skal slettes

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/helperFunctions/ingredientHelper.js
> +/**
what is this?

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/FullRecipeView.jsx
> -        <h2>Ingredienser:</h2>
så skal det her gendannes

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/pages/FullRecipeView.jsx
> +        <h4>Ialt: {finalRecipesSum.toFixed(2)},-</h4>
kan der ikke stå:
Pris i alt:

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/testdata/recipeTest.json
> +{
delete plz

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/testdata/testrescipes.json
> +[
also this

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.RestApi/Controllers/PublicControllerV1.cs
> +        Console.WriteLine("recipe: ", recipe);
maybe delete

2023-12-12 09:35 UTC, Lildhansen commented on P7Internet.RestApi/Controllers/PublicControllerV1.cs
> +        Console.WriteLine(result);
de her skal slettes

2023-12-12 09:51 UTC, Casper0913 commented
<img width="649" alt="Skærmbillede 2023-12-12 kl  10 47 29" src="https://github.com/Jaffenheimer/p7-internet/assets/48017776/46900fb5-6ec2-48c1-8a52-6f91be23dcf4">

<img width="928" alt="Skærmbillede 2023-12-12 kl  10 48 33" src="https://github.com/Jaffenheimer/p7-internet/assets/48017776/9c4e70cc-5e31-421d-856f-056c5692b0bf">

<img width="226" alt="Skærmbillede 2023-12-12 kl  10 49 02" src="https://github.com/Jaffenheimer/p7-internet/assets/48017776/a34cf3d7-8a67-421e-b0e1-5d7201708fef">

Når jeg prøver med en opskrift med 11 ingredienser, så få en en fejl fordi den har bedt om for mange ingredienser. Alle mine kommer også fra bilkaToGo og den tilføjer også ingredienser igen, selvom den har tilført den. 

Er vi nød til at be ChatGPT om at lave en mindre opskrift og skal vi have errorhandling på det?

2023-12-12 10:14 UTC, JJTM20 commented
> <img alt="Skærmbillede 2023-12-12 kl 10 47 29" width="649" src="https://private-user-images.githubusercontent.com/48017776/289815833-46900fb5-6ec2-48c1-8a52-6f91be23dcf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzYwODgsIm5iZiI6MTcwMjM3NTc4OCwicGF0aCI6Ii80ODAxNzc3Ni8yODk4MTU4MzMtNDY5MDBmYjUtNmVjMi00OGMxLThhNTItNmY5MWJlMjNkY2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDEwMDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YjY0MmI0YzJlNzM4OTk1ZmViZThiNTA4OWQxMDJmOTYxZDBmZTYxMjJjMTdiNGRmMmZjNGYzZGZhOTA4YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bF3UZuaNlgqRVki3OQFa23UGGfeRsCAZ2rMlTPuQZus"> <img alt="Skærmbillede 2023-12-12 kl 10 48 33" width="928" src="https://private-user-images.githubusercontent.com/48017776/289816113-9c4e70cc-5e31-421d-856f-056c5692b0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzYwODgsIm5iZiI6MTcwMjM3NTc4OCwicGF0aCI6Ii80ODAxNzc3Ni8yODk4MTYxMTMtOWM0ZTcwY2MtNWUzMS00MjFkLTg1NmYtMDU2YzU2OTJiMGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDEwMDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYzdjZWIyYThiY2M0NzA0MzljZWJmNDE1MmY5ZWMyMTI3M2M4ZGM2MTQxMTg1ODg2OWI3ZGQwNWRjZDNlNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hMzoRsaDfOb_Y5wn8ynHcbIFx1IDBTqaq3vncZkV2xc"> <img alt="Skærmbillede 2023-12-12 kl 10 49 02" width="226" src="https://private-user-images.githubusercontent.com/48017776/289816248-a34cf3d7-8a67-421e-b0e1-5d7201708fef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzYwODgsIm5iZiI6MTcwMjM3NTc4OCwicGF0aCI6Ii80ODAxNzc3Ni8yODk4MTYyNDgtYTM0Y2YzZDctOGE2Ny00MjFlLWIwZTEtNWQ3MjAxNzA4ZmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDEwMDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYWQ2MGQyMTRhODI3MDUwNTY4NzhiYjgxNTJmZjQ4Y2RjMDczMThlNzhlMmRjMWNmMTVmOGNlYTJmOWQ3MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.22wpMHjXAer9GHshCPnF1tOH3JCXgSqCe_S-JsFNjc0">
> Når jeg prøver med en opskrift med 11 ingredienser, så få en en fejl fordi den har bedt om for mange ingredienser. Alle mine kommer også fra bilkaToGo og den tilføjer også ingredienser igen, selvom den har tilført den.
> 
> Er vi nød til at be ChatGPT om at lave en mindre opskrift og skal vi have errorhandling på det?

Kan godt forsøge at lave noget hokus pokus så der er lidt ventetid imellem requests, men det kan jo godt ende ud med at der skal gå flere sekunder mellem hver bulk af requests.. Og det ved jeg ikke om vi er interesserede i?

2023-12-12 10:41 UTC, Casper0913 commented
> > <img alt="Skærmbillede 2023-12-12 kl 10 47 29" width="649" src="https://private-user-images.githubusercontent.com/48017776/289815833-46900fb5-6ec2-48c1-8a52-6f91be23dcf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzYwODgsIm5iZiI6MTcwMjM3NTc4OCwicGF0aCI6Ii80ODAxNzc3Ni8yODk4MTU4MzMtNDY5MDBmYjUtNmVjMi00OGMxLThhNTItNmY5MWJlMjNkY2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDEwMDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YjY0MmI0YzJlNzM4OTk1ZmViZThiNTA4OWQxMDJmOTYxZDBmZTYxMjJjMTdiNGRmMmZjNGYzZGZhOTA4YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bF3UZuaNlgqRVki3OQFa23UGGfeRsCAZ2rMlTPuQZus"> <img alt="Skærmbillede 2023-12-12 kl 10 48 33" width="928" src="https://private-user-images.githubusercontent.com/48017776/289816113-9c4e70cc-5e31-421d-856f-056c5692b0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzYwODgsIm5iZiI6MTcwMjM3NTc4OCwicGF0aCI6Ii80ODAxNzc3Ni8yODk4MTYxMTMtOWM0ZTcwY2MtNWUzMS00MjFkLTg1NmYtMDU2YzU2OTJiMGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDEwMDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYzdjZWIyYThiY2M0NzA0MzljZWJmNDE1MmY5ZWMyMTI3M2M4ZGM2MTQxMTg1ODg2OWI3ZGQwNWRjZDNlNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hMzoRsaDfOb_Y5wn8ynHcbIFx1IDBTqaq3vncZkV2xc"> <img alt="Skærmbillede 2023-12-12 kl 10 49 02" width="226" src="https://private-user-images.githubusercontent.com/48017776/289816248-a34cf3d7-8a67-421e-b0e1-5d7201708fef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzYwODgsIm5iZiI6MTcwMjM3NTc4OCwicGF0aCI6Ii80ODAxNzc3Ni8yODk4MTYyNDgtYTM0Y2YzZDctOGE2Ny00MjFlLWIwZTEtNWQ3MjAxNzA4ZmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDEwMDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYWQ2MGQyMTRhODI3MDUwNTY4NzhiYjgxNTJmZjQ4Y2RjMDczMThlNzhlMmRjMWNmMTVmOGNlYTJmOWQ3MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.22wpMHjXAer9GHshCPnF1tOH3JCXgSqCe_S-JsFNjc0">
> > Når jeg prøver med en opskrift med 11 ingredienser, så få en en fejl fordi den har bedt om for mange ingredienser. Alle mine kommer også fra bilkaToGo og den tilføjer også ingredienser igen, selvom den har tilført den.
> > Er vi nød til at be ChatGPT om at lave en mindre opskrift og skal vi have errorhandling på det?
> 
> Kan godt forsøge at lave noget hokus pokus så der er lidt ventetid imellem requests, men det kan jo godt ende ud med at der skal gå flere sekunder mellem hver bulk af requests.. Og det ved jeg ikke om vi er interesserede i?

Det virker for mig nu, dog så viser den ingredienser som ikke findes i opskriten. 

Dog for jeg nogle ingredienser, hvor der kun er har prisen. Grunden til det er at shortingredient finder alle ingredienser fra den stringen som den for fra openAI og hvis en ingredienser er i metoder så er den ikke i ingredienser, men i shortingredient.
<img width="1428" alt="Skærmbillede 2023-12-12 kl  11 39 05" src="https://github.com/Jaffenheimer/p7-internet/assets/48017776/b20607b6-6212-4165-92a7-86b713ccb176">

2023-12-17 11:40 UTC, Lildhansen approved these changes

2023-12-17 11:50 UTC, merged