Number field CSS looks better now
Jaffenheimer/p7-internet pull request #31
Opened 2023-10-05 10:14 UTC by NikolajKrogh

Created buttons for number field and did some CSS

2023-10-05 10:29 UTC, Lildhansen commented
number field er ret vague. er det persons?

2023-10-05 10:31 UTC, Lildhansen commented
det er ret træls der kommer en popup op når man skriver værdier under eller over (kunne være bedre hvis det bare stod lige under feltet.
ellers når man bruger textfeltet og sletter det der står kommer der en popup

fx hvis du vil skrive 3, skal du skrive 13 og så slette 1'et.

2023-10-05 10:32 UTC, Lildhansen commented
det burder også først være et problem når du exitter feltet, ikke når man er inde i feltet

2023-10-05 10:33 UTC, Lildhansen commented
og hvis du bruger minus og plus omkring grænseværdierne (100 og 0) kan man gå under 0 og op til et meget højt tal

2023-10-05 10:35 UTC, Lildhansen commented
og nogle gange hvis man trykker +, tilføjer den bare et ciffer (fx skrev jeg 1, og så trykker jeg plus og så står der 11)

2023-10-05 10:41 UTC, Lildhansen requested changes
pt er der et par bugs i fht feltet (se kommentarer over).

altså for min skyld kan vi jo også bare have et normalt tekstfelt, men hvis I er fan af det plus minus kan vi godt gøre det

2023-10-05 10:41 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/ContainerRight.jsx
> +      <div className='ContainerRightTop'>
er der en grund til at dele det op på denne måde. vi har vel ikke en bottom også.
synes godt bare denne div kan slettes

2023-10-05 10:41 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/NumberField.jsx
> +    setValue(value + 1);
her mangler lidt tjek på om værdien er over 100 (og for subtract, under 1)

2023-10-05 10:42 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/App.css
> +.ContainerRight > .ContainerRightTop > .containerRightColumn > .ProfilePicture > img {
er der en grund til vi ikke bare skriver profilepicture?

2023-10-05 10:43 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/App.css
> +.ContainerRight > .ContainerRightTop > .containerRightColumn > .ProfilePicture > img {
altså uden at det skal være child af alt muligt.
hvis vi så engang får et andet element som vi også gerne vil kalde profilepicture, kan vi så kigge på det der, og give dem forskellige navne

2023-10-05 10:49 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/App.css
> +.ContainerRight > .ContainerRightTop > .containerRightColumn > .ProfilePicture > img {
Ja grunden er CSS - vi vil gerne have det til at stå pænt i forhold til det andet. Så det fungerer ikke bare at skrive .ProfilePicture

2023-10-05 10:50 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/components/ContainerRight.jsx
> +      <div className='ContainerRightTop'>
Ja der kommer mere som måske kommer til at hedde middle og nok også en der hedder bottom de er bare ikke lavet endnu

2023-10-05 10:57 UTC, NikolajKrogh commented
> number field er ret vague. er det persons?

Nej det er <type="number"/> Det har ingenting med persons at gøre. Det er kun et field hvor du kan skrive tal

2023-10-05 11:02 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/components/NumberField.jsx
> +    setValue(value + 1);
Ja det kan jeg godt se og tilføjer jeg

2023-10-05 11:58 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/App.css
> +.ContainerRight > .ContainerRightTop > .containerRightColumn > .ProfilePicture > img {
jo, fordi hvis du gerne vil ændre et billede som er et child af profilePicture-klassen, kan man lige så godt bare skrive det her:
- .ProfilePicture > img
den eneste forskel ved den lange smøre er at hvis vi får 2 klasser der hedder profile picture vil den ændre for dem begge, men kan ikke se hvordan vi får et andet profile picture som skal se anderledes ud, og selv hvis vi gør vil jeg foretrække bare at ændre navnet på klassen

2023-10-05 11:59 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/App.css
> +.ContainerRight > .ContainerRightTop > .containerRightColumn > .ProfilePicture > img {
det at du skriver alt det her:
- **.ContainerRight > .ContainerRightTop > .containerRightColumn > .ProfilePicture ** > img
ændrer kun på billedet

2023-10-05 12:00 UTC, Lildhansen commented on P7Internet.Frontend/react-app/src/components/NumberField.jsx
> +    setValue(value + 1);
og tror at når du skriver noget i tekstfeltet bliver det til en string, fordi når du så trykker plus tilføjer den bare 1 efter (altså det med at 1 bliver til 11)

2023-10-05 12:09 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/App.css
> +.ContainerRight > .ContainerRightTop > .containerRightColumn > .ProfilePicture > img {
Okay kan godt fjerne det, men så fjerner jeg det også alle de andre steder

2023-10-05 12:59 UTC, NikolajKrogh commented
> det er ret træls der kommer en popup op når man skriver værdier under eller over (kunne være bedre hvis det bare stod lige under feltet. ellers når man bruger textfeltet og sletter det der står kommer der en popup
> 
> fx hvis du vil skrive 3, skal du skrive 13 og så slette 1'et.

Nu kan du ikke skrive noget i feltet og skal bruge "+" eller "-"

Beholder den pop-up, fordi jeg kan ikke få lov til at installere et nyt module som jeg tænker vi skal bruge. Det kan oprettes som et issue, hvis der er nogle der lyst til at sidde og rode med det

2023-10-06 06:42 UTC, NikolajKrogh commented on P7Internet.Frontend/react-app/src/components/NumberField.jsx
> +    setValue(value + 1);
Det gør den ikke

2023-10-06 09:50 UTC, Lildhansen commented
det ser fint ud nu, udover at alerten siger max er 100, men logisk er det max er 10

2023-10-09 06:43 UTC, sebxGit commented
Jeg er ikke helt sikker på, om det er med vilje, men jeg kan ihf. ikke indsætte tal vha. input feltet på min mac (altså uden brug af + og -).

2023-10-10 09:03 UTC, Lildhansen approved these changes
sgutm

2023-10-10 09:06 UTC, merged